import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class SimuhireSession(Base):
    __tablename__ = "simuhire_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    candidate_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # null = self-initiated; set if employer triggered (future feature)
    employer_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    # 'technical' | 'business' | 'general'
    simulation_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # 'active' | 'completed'
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    # 'Scope Creeper' | 'Sceptic' | 'Escalator'
    stakeholder_persona: Mapped[Optional[str]] = mapped_column(String(100))

    # Full conversation history: [{speaker, text, input_mode, timestamp}, ...]
    # input_mode: 'text' | 'audio' — supports mixed-mode sessions (F6 audio requirement)
    conversation: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # Set once by Evaluator agent at session end (never per-message)
    evaluator_scores: Mapped[Optional[dict]] = mapped_column(JSONB)
    overall_score: Mapped[Optional[int]] = mapped_column(Integer)

    # Generated by Feedback agent from Evaluator's evidence quotes
    report: Mapped[Optional[dict]] = mapped_column(JSONB)

    candidate_shared: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    retake_available_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True)
    )  # completed_at + 7 days

    # Relationships
    candidate: Mapped["User"] = relationship(
        foreign_keys=[candidate_id], back_populates="simuhire_sessions"
    )
